# Generated by Django 4.0.3 on 2022-04-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='subjects',
            field=models.ManyToManyField(related_name='doctorsubject', to='exam.subject'),
        ),
    ]
