# Generated by Django 4.0.4 on 2022-04-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_professor_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='subjects',
            field=models.ManyToManyField(to='exam.subject'),
        ),
    ]
