# Generated by Django 4.0.4 on 2022-04-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_professor_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='subjects',
        ),
    ]
