# Generated by Django 4.0.4 on 2022-04-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_remove_professor_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='subjects',
            field=models.ManyToManyField(to='exam.subject'),
        ),
    ]
