# Generated by Django 4.0.4 on 2022-04-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_professor_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
