# Generated by Django 4.0.4 on 2022-04-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_examquestion_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightanswer',
            options={'ordering': ['questions']},
        ),
    ]
