# Generated by Django 4.0.4 on 2022-04-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_alter_rightanswer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/images')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='exam.person')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exam.question')),
            ],
        ),
    ]
