# Generated by Django 4.0.4 on 2022-04-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='person',
        ),
        migrations.AddField(
            model_name='image',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='exam.student'),
        ),
    ]
