# Generated by Django 4.0.4 on 2022-04-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_student_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
    ]
