# Generated by Django 4.0.4 on 2022-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_remove_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
