# Generated by Django 4.0.4 on 2022-05-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_remove_chapter_subject_chapter_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ManyToManyField(to='exam.subject'),
        ),
    ]
