# Generated by Django 4.0.4 on 2022-05-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_alter_chapter_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='chapters',
            field=models.ManyToManyField(to='exam.chapter'),
        ),
    ]
