# Generated by Django 4.0.4 on 2022-05-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_remove_chapter_subject_subject_chapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='chapters',
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ManyToManyField(to='exam.subject'),
        ),
    ]
