# Generated by Django 4.0.4 on 2022-05-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_remove_chapter_subject_chapter_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ManyToManyField(related_name='chapters', to='exam.subject'),
        ),
    ]
