# Generated by Django 4.0.4 on 2022-05-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0036_alter_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='inputType',
            field=models.CharField(choices=[('radio', 'radio'), ('checkbox', 'checkbox')], default='radio', max_length=8),
            preserve_default=False,
        ),
    ]
