# Generated by Django 4.0.4 on 2022-05-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0038_alter_answer_title_alter_chapter_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Answer'),
        ),
    ]
