# Generated by Django 4.0.4 on 2022-05-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0039_alter_answer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rightanswers', to='exam.question'),
        ),
    ]
