# Generated by Django 4.0.4 on 2022-04-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('STD', 'Student'), ('PRF', 'Professor')], max_length=3, null=True),
        ),
    ]
